# numpy
NumPy is the fundamental package for scientific computing with Python. It contains among other things:

* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

NumPy is licensed under the BSD license, enabling reuse with few restrictions.

In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.dtype

dtype('int64')

In [6]:
a.dtype.name

'int64'

In [7]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [8]:
np.arange(1, 7)

array([1, 2, 3, 4, 5, 6])

In [9]:
new_a = np.array([4,5,2,8,6,9,6,3])

In [10]:
new_a

array([4, 5, 2, 8, 6, 9, 6, 3])

In [11]:
new_a.shape

(8,)

In [12]:
new_a.sum()

43

In [13]:
new_a.min()

2

In [14]:
new_a.max()

9

In [15]:
# create list of random numbers
import random
random_list = []
for x in range(100):
    random_list.append(random.randint(1, 400))
print(random_list)

[51, 38, 110, 24, 391, 221, 153, 61, 184, 21, 236, 122, 205, 382, 209, 72, 187, 388, 356, 144, 396, 109, 356, 155, 252, 56, 292, 80, 316, 194, 167, 59, 350, 115, 332, 175, 299, 228, 161, 127, 91, 272, 188, 90, 17, 359, 214, 259, 18, 77, 387, 255, 132, 319, 101, 80, 54, 200, 276, 369, 378, 7, 295, 15, 141, 391, 242, 395, 70, 269, 123, 77, 247, 17, 398, 226, 34, 198, 149, 397, 241, 116, 319, 254, 356, 151, 286, 370, 230, 28, 30, 377, 359, 217, 330, 259, 44, 211, 384, 239]


In [16]:
numpy_random_builtin = np.random.random((100,))

In [17]:
numpy_random_builtin

array([0.17273483, 0.65451903, 0.20463298, 0.8260582 , 0.68553825,
       0.91262481, 0.96064848, 0.57468104, 0.26472374, 0.84505298,
       0.4494602 , 0.82598434, 0.46151842, 0.0024705 , 0.08441556,
       0.19549673, 0.06486763, 0.31548511, 0.88687887, 0.13561427,
       0.27438607, 0.24870063, 0.57206922, 0.93883712, 0.58581975,
       0.32581994, 0.08311931, 0.67193235, 0.52375569, 0.93887427,
       0.87422498, 0.52758474, 0.44947785, 0.50466407, 0.43785955,
       0.72882964, 0.99474115, 0.79382934, 0.86130692, 0.93296839,
       0.74422461, 0.40956698, 0.62224321, 0.19020029, 0.01384618,
       0.55196474, 0.32424606, 0.8376786 , 0.41798607, 0.97930024,
       0.42163633, 0.53322879, 0.57397759, 0.26406704, 0.59105883,
       0.96039015, 0.25682459, 0.31999329, 0.03769497, 0.0710584 ,
       0.6043752 , 0.41330908, 0.63479106, 0.92165657, 0.95513894,
       0.74478746, 0.21285282, 0.77415749, 0.10533776, 0.36692763,
       0.20763495, 0.52401148, 0.52959258, 0.84929907, 0.96399

In [18]:
numpy_random_builtin * 1000

array([172.73482933, 654.5190301 , 204.63298121, 826.05820238,
       685.53824527, 912.62481361, 960.64847999, 574.68104428,
       264.72374288, 845.05298022, 449.46019878, 825.98434258,
       461.51842002,   2.4705025 ,  84.41556436, 195.49673067,
        64.86763367, 315.4851111 , 886.87886726, 135.6142709 ,
       274.38606563, 248.70063185, 572.06921533, 938.83711778,
       585.81974873, 325.81994347,  83.11930588, 671.93234578,
       523.7556947 , 938.87427055, 874.22497822, 527.58474322,
       449.47784999, 504.66407327, 437.85954744, 728.8296398 ,
       994.74114989, 793.82934124, 861.30692015, 932.96838973,
       744.22461331, 409.56697624, 622.24320533, 190.20029338,
        13.84617899, 551.96473602, 324.24606358, 837.67859673,
       417.98607105, 979.30024336, 421.63633202, 533.22879114,
       573.97759152, 264.06704271, 591.05883075, 960.39015126,
       256.82459117, 319.99329085,  37.69496816,  71.05839632,
       604.37520426, 413.3090844 , 634.79105793, 921.65

In [19]:
numpy_random_builtin

array([0.17273483, 0.65451903, 0.20463298, 0.8260582 , 0.68553825,
       0.91262481, 0.96064848, 0.57468104, 0.26472374, 0.84505298,
       0.4494602 , 0.82598434, 0.46151842, 0.0024705 , 0.08441556,
       0.19549673, 0.06486763, 0.31548511, 0.88687887, 0.13561427,
       0.27438607, 0.24870063, 0.57206922, 0.93883712, 0.58581975,
       0.32581994, 0.08311931, 0.67193235, 0.52375569, 0.93887427,
       0.87422498, 0.52758474, 0.44947785, 0.50466407, 0.43785955,
       0.72882964, 0.99474115, 0.79382934, 0.86130692, 0.93296839,
       0.74422461, 0.40956698, 0.62224321, 0.19020029, 0.01384618,
       0.55196474, 0.32424606, 0.8376786 , 0.41798607, 0.97930024,
       0.42163633, 0.53322879, 0.57397759, 0.26406704, 0.59105883,
       0.96039015, 0.25682459, 0.31999329, 0.03769497, 0.0710584 ,
       0.6043752 , 0.41330908, 0.63479106, 0.92165657, 0.95513894,
       0.74478746, 0.21285282, 0.77415749, 0.10533776, 0.36692763,
       0.20763495, 0.52401148, 0.52959258, 0.84929907, 0.96399

In [20]:
np.asarray(numpy_random_builtin * 10000, dtype=int)

array([1727, 6545, 2046, 8260, 6855, 9126, 9606, 5746, 2647, 8450, 4494,
       8259, 4615,   24,  844, 1954,  648, 3154, 8868, 1356, 2743, 2487,
       5720, 9388, 5858, 3258,  831, 6719, 5237, 9388, 8742, 5275, 4494,
       5046, 4378, 7288, 9947, 7938, 8613, 9329, 7442, 4095, 6222, 1902,
        138, 5519, 3242, 8376, 4179, 9793, 4216, 5332, 5739, 2640, 5910,
       9603, 2568, 3199,  376,  710, 6043, 4133, 6347, 9216, 9551, 7447,
       2128, 7741, 1053, 3669, 2076, 5240, 5295, 8492, 9639, 4054, 9250,
       8643,  812, 6572, 7926, 7047, 6343, 6265, 6028, 1269,  495, 3855,
       5543, 9155, 1473, 5203, 7374, 9797, 1367, 2900,  239,  557, 5993,
       4993])