# numpy
NumPy is the fundamental package for scientific computing with Python. It contains among other things:

* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

NumPy is licensed under the BSD license, enabling reuse with few restrictions.

In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.dtype

dtype('int64')

In [6]:
a.dtype.name

'int64'

In [7]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [8]:
np.arange(1, 7)

array([1, 2, 3, 4, 5, 6])

In [9]:
new_a = np.array([4,5,2,8,6,9,6,3])

In [10]:
new_a

array([4, 5, 2, 8, 6, 9, 6, 3])

In [11]:
new_a.shape

(8,)

In [12]:
new_a.sum()

43

In [13]:
new_a.min()

2

In [14]:
new_a.max()

9

In [15]:
# create list of random numbers
import random
random_list = []
for x in range(100):
    random_list.append(random.randint(1, 400))
print(random_list)

[204, 235, 243, 177, 272, 161, 383, 92, 7, 64, 142, 191, 43, 371, 145, 87, 392, 310, 24, 222, 372, 349, 348, 77, 219, 124, 293, 117, 397, 152, 342, 28, 324, 36, 369, 126, 210, 137, 4, 310, 31, 211, 134, 182, 289, 47, 176, 170, 318, 46, 310, 30, 114, 185, 138, 209, 176, 391, 58, 297, 231, 158, 243, 24, 386, 284, 254, 52, 305, 121, 340, 72, 49, 166, 35, 310, 90, 248, 87, 79, 325, 276, 194, 247, 208, 40, 90, 132, 301, 74, 306, 9, 57, 39, 207, 226, 153, 394, 308, 21]


In [16]:
numpy_random_builtin = np.random.random((100,))

In [17]:
numpy_random_builtin

array([0.60872133, 0.58678921, 0.0788491 , 0.13626478, 0.67552122,
       0.19398872, 0.08311666, 0.26273487, 0.24150452, 0.58973144,
       0.71755984, 0.88708427, 0.83644858, 0.0278085 , 0.18990594,
       0.45537494, 0.34999728, 0.72358202, 0.62336429, 0.24645001,
       0.03309719, 0.49409085, 0.11245754, 0.26669248, 0.88599993,
       0.26129075, 0.91000561, 0.82076961, 0.62519699, 0.13155614,
       0.11222979, 0.94682718, 0.25533221, 0.92099649, 0.28020466,
       0.66141605, 0.96855091, 0.08141411, 0.36204438, 0.48862492,
       0.43473344, 0.60887841, 0.8688944 , 0.88643646, 0.6643738 ,
       0.82980908, 0.55348152, 0.96806352, 0.9200499 , 0.87471619,
       0.94556743, 0.578832  , 0.76957492, 0.66084451, 0.28374299,
       0.68229005, 0.82829102, 0.7165369 , 0.33262799, 0.55888791,
       0.93843986, 0.91941242, 0.59037755, 0.46959629, 0.77794556,
       0.0562519 , 0.90269736, 0.33901907, 0.22345231, 0.07737253,
       0.08608884, 0.82680719, 0.36075402, 0.45167821, 0.81510

In [18]:
numpy_random_builtin * 1000

array([608.72132785, 586.78921365,  78.84910171, 136.26477508,
       675.52122156, 193.98871983,  83.11666221, 262.73487483,
       241.50452089, 589.73143986, 717.55983545, 887.08427037,
       836.44857513,  27.80850408, 189.90594303, 455.37494164,
       349.9972789 , 723.58201609, 623.36429318, 246.4500146 ,
        33.09719027, 494.09084663, 112.4575404 , 266.69248176,
       885.99993013, 261.29074688, 910.00561242, 820.76960676,
       625.19698629, 131.55614049, 112.22979295, 946.82717513,
       255.33221186, 920.9964875 , 280.20466201, 661.41605309,
       968.55091484,  81.41411375, 362.0443829 , 488.62492183,
       434.73344094, 608.87840829, 868.89440391, 886.4364609 ,
       664.37379586, 829.8090756 , 553.48151836, 968.06351631,
       920.04990174, 874.71618915, 945.56743379, 578.83200005,
       769.57491888, 660.84451382, 283.74299322, 682.29004884,
       828.29102453, 716.5368958 , 332.62799479, 558.8879065 ,
       938.43985879, 919.41242175, 590.37755072, 469.59

In [19]:
numpy_random_builtin

array([0.60872133, 0.58678921, 0.0788491 , 0.13626478, 0.67552122,
       0.19398872, 0.08311666, 0.26273487, 0.24150452, 0.58973144,
       0.71755984, 0.88708427, 0.83644858, 0.0278085 , 0.18990594,
       0.45537494, 0.34999728, 0.72358202, 0.62336429, 0.24645001,
       0.03309719, 0.49409085, 0.11245754, 0.26669248, 0.88599993,
       0.26129075, 0.91000561, 0.82076961, 0.62519699, 0.13155614,
       0.11222979, 0.94682718, 0.25533221, 0.92099649, 0.28020466,
       0.66141605, 0.96855091, 0.08141411, 0.36204438, 0.48862492,
       0.43473344, 0.60887841, 0.8688944 , 0.88643646, 0.6643738 ,
       0.82980908, 0.55348152, 0.96806352, 0.9200499 , 0.87471619,
       0.94556743, 0.578832  , 0.76957492, 0.66084451, 0.28374299,
       0.68229005, 0.82829102, 0.7165369 , 0.33262799, 0.55888791,
       0.93843986, 0.91941242, 0.59037755, 0.46959629, 0.77794556,
       0.0562519 , 0.90269736, 0.33901907, 0.22345231, 0.07737253,
       0.08608884, 0.82680719, 0.36075402, 0.45167821, 0.81510

In [20]:
np.asarray(numpy_random_builtin * 10000, dtype=int)

array([6087, 5867,  788, 1362, 6755, 1939,  831, 2627, 2415, 5897, 7175,
       8870, 8364,  278, 1899, 4553, 3499, 7235, 6233, 2464,  330, 4940,
       1124, 2666, 8859, 2612, 9100, 8207, 6251, 1315, 1122, 9468, 2553,
       9209, 2802, 6614, 9685,  814, 3620, 4886, 4347, 6088, 8688, 8864,
       6643, 8298, 5534, 9680, 9200, 8747, 9455, 5788, 7695, 6608, 2837,
       6822, 8282, 7165, 3326, 5588, 9384, 9194, 5903, 4695, 7779,  562,
       9026, 3390, 2234,  773,  860, 8268, 3607, 4516, 8151, 4324, 4280,
       2792, 2679, 6198, 8773, 8581, 9049, 5056, 3660, 8608, 8880, 4914,
       9497, 4578, 2894, 2745, 7228,  668, 9768, 7674,  182,  411, 3553,
        850])