# numpy
NumPy is the fundamental package for scientific computing with Python. It contains among other things:

* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

NumPy is licensed under the BSD license, enabling reuse with few restrictions.

In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.dtype

dtype('int64')

In [6]:
a.dtype.name

'int64'

In [7]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [8]:
np.arange(1, 7)

array([1, 2, 3, 4, 5, 6])

In [9]:
new_a = np.array([4,5,2,8,6,9,6,3])

In [10]:
new_a

array([4, 5, 2, 8, 6, 9, 6, 3])

In [11]:
new_a.shape

(8,)

In [12]:
new_a.sum()

43

In [13]:
new_a.min()

2

In [14]:
new_a.max()

9

In [15]:
# create list of random numbers
import random
random_list = []
for x in range(100):
    random_list.append(random.randint(1, 400))
print(random_list)

[176, 155, 108, 87, 207, 358, 225, 310, 329, 217, 6, 93, 120, 166, 56, 57, 50, 217, 13, 232, 374, 250, 49, 391, 213, 31, 78, 53, 105, 256, 129, 357, 277, 395, 197, 132, 25, 317, 269, 95, 146, 32, 193, 45, 210, 324, 19, 251, 379, 168, 297, 285, 137, 256, 230, 37, 49, 205, 80, 219, 299, 389, 139, 157, 291, 115, 314, 23, 209, 282, 112, 236, 377, 206, 368, 252, 51, 261, 101, 336, 49, 33, 395, 272, 320, 374, 66, 104, 216, 108, 247, 66, 369, 100, 388, 73, 11, 396, 268, 278]


In [16]:
numpy_random_builtin = np.random.random((100,))

In [17]:
numpy_random_builtin

array([2.73766078e-01, 4.94911062e-01, 8.56533428e-01, 1.88519473e-01,
       4.17203569e-01, 7.92797607e-01, 7.33917075e-01, 8.47471550e-01,
       5.10977075e-01, 4.48745268e-01, 1.68683458e-02, 6.78908983e-01,
       6.06592498e-01, 9.77683591e-01, 8.15857973e-01, 5.96364040e-01,
       4.20895251e-01, 7.03764400e-01, 9.56662537e-01, 5.17057475e-01,
       6.79532351e-01, 2.57796104e-01, 1.13597750e-01, 5.89184140e-01,
       2.97105263e-01, 9.22650627e-01, 3.68888390e-02, 6.52584823e-01,
       9.57114544e-01, 3.74874268e-01, 9.13187445e-01, 6.41547841e-01,
       5.73452801e-01, 8.44999813e-01, 5.65774438e-01, 1.80307190e-01,
       2.98534754e-01, 5.35787728e-01, 4.91502856e-01, 9.24237291e-01,
       5.39192137e-01, 7.13970442e-01, 2.65816482e-01, 2.18567808e-01,
       1.49535047e-02, 1.99685118e-01, 2.89298486e-02, 3.97391303e-01,
       6.57458981e-01, 7.31045102e-01, 7.16794076e-01, 8.80208317e-01,
       6.59298938e-01, 6.38457756e-01, 9.66543588e-01, 9.23141658e-01,
      

In [18]:
numpy_random_builtin * 1000

array([2.73766078e+02, 4.94911062e+02, 8.56533428e+02, 1.88519473e+02,
       4.17203569e+02, 7.92797607e+02, 7.33917075e+02, 8.47471550e+02,
       5.10977075e+02, 4.48745268e+02, 1.68683458e+01, 6.78908983e+02,
       6.06592498e+02, 9.77683591e+02, 8.15857973e+02, 5.96364040e+02,
       4.20895251e+02, 7.03764400e+02, 9.56662537e+02, 5.17057475e+02,
       6.79532351e+02, 2.57796104e+02, 1.13597750e+02, 5.89184140e+02,
       2.97105263e+02, 9.22650627e+02, 3.68888390e+01, 6.52584823e+02,
       9.57114544e+02, 3.74874268e+02, 9.13187445e+02, 6.41547841e+02,
       5.73452801e+02, 8.44999813e+02, 5.65774438e+02, 1.80307190e+02,
       2.98534754e+02, 5.35787728e+02, 4.91502856e+02, 9.24237291e+02,
       5.39192137e+02, 7.13970442e+02, 2.65816482e+02, 2.18567808e+02,
       1.49535047e+01, 1.99685118e+02, 2.89298486e+01, 3.97391303e+02,
       6.57458981e+02, 7.31045102e+02, 7.16794076e+02, 8.80208317e+02,
       6.59298938e+02, 6.38457756e+02, 9.66543588e+02, 9.23141658e+02,
      

In [19]:
numpy_random_builtin

array([2.73766078e-01, 4.94911062e-01, 8.56533428e-01, 1.88519473e-01,
       4.17203569e-01, 7.92797607e-01, 7.33917075e-01, 8.47471550e-01,
       5.10977075e-01, 4.48745268e-01, 1.68683458e-02, 6.78908983e-01,
       6.06592498e-01, 9.77683591e-01, 8.15857973e-01, 5.96364040e-01,
       4.20895251e-01, 7.03764400e-01, 9.56662537e-01, 5.17057475e-01,
       6.79532351e-01, 2.57796104e-01, 1.13597750e-01, 5.89184140e-01,
       2.97105263e-01, 9.22650627e-01, 3.68888390e-02, 6.52584823e-01,
       9.57114544e-01, 3.74874268e-01, 9.13187445e-01, 6.41547841e-01,
       5.73452801e-01, 8.44999813e-01, 5.65774438e-01, 1.80307190e-01,
       2.98534754e-01, 5.35787728e-01, 4.91502856e-01, 9.24237291e-01,
       5.39192137e-01, 7.13970442e-01, 2.65816482e-01, 2.18567808e-01,
       1.49535047e-02, 1.99685118e-01, 2.89298486e-02, 3.97391303e-01,
       6.57458981e-01, 7.31045102e-01, 7.16794076e-01, 8.80208317e-01,
       6.59298938e-01, 6.38457756e-01, 9.66543588e-01, 9.23141658e-01,
      

In [20]:
np.asarray(numpy_random_builtin * 10000, dtype=int)

array([2737, 4949, 8565, 1885, 4172, 7927, 7339, 8474, 5109, 4487,  168,
       6789, 6065, 9776, 8158, 5963, 4208, 7037, 9566, 5170, 6795, 2577,
       1135, 5891, 2971, 9226,  368, 6525, 9571, 3748, 9131, 6415, 5734,
       8449, 5657, 1803, 2985, 5357, 4915, 9242, 5391, 7139, 2658, 2185,
        149, 1996,  289, 3973, 6574, 7310, 7167, 8802, 6592, 6384, 9665,
       9231, 7816, 5430, 9173, 7096, 3489, 5705, 8452, 1832, 9851, 5481,
       7945, 9644, 5749, 7377, 7220, 9825, 2988, 1330, 3405, 2478,  341,
          7, 8060, 8146, 7555, 7901, 6028,  814, 1419, 9273, 3040, 5390,
       1698, 4502,  693, 4229, 7586, 1936, 8828, 2384, 4904, 8364, 4148,
       3950])